// Singapore Amenities POI Seed Dataset
// Coordinates collected from Singapore SLA OneMap, LTA DataMall, MOE, NEA datasets

export const seedAmenitiesData = [
  // ==================== 🚆 MRT STATIONS ====================
  // Downtown Line (DTL - Blue Line) 🔵
  { category: 'mrt', name: 'Bukit Panjang MRT (DT1/BP6)', latitude: 1.3784, longitude: 103.7617, details: JSON.stringify({ lines: ['DTL', 'LRT'], interchange: true }) },
  { category: 'mrt', name: 'Cashew MRT (DT2)', latitude: 1.3698, longitude: 103.7644, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Hillview MRT (DT3)', latitude: 1.3623, longitude: 103.7674, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Beauty World MRT (DT5)', latitude: 1.3412, longitude: 103.7758, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'King Albert Park MRT (DT6)', latitude: 1.3357, longitude: 103.7834, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Sixth Avenue MRT (DT7)', latitude: 1.3308, longitude: 103.7969, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Tan Kah Kee MRT (DT8)', latitude: 1.3260, longitude: 103.8066, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Botanic Gardens MRT (DT9/CC19)', latitude: 1.3225, longitude: 103.8153, details: JSON.stringify({ lines: ['DTL', 'CCL'], interchange: true }) },
  { category: 'mrt', name: 'Stevens MRT (DT10/TE11)', latitude: 1.3200, longitude: 103.8260, details: JSON.stringify({ lines: ['DTL', 'TEL'], interchange: true }) },
  { category: 'mrt', name: 'Newton MRT (NS21/DT11)', latitude: 1.3123, longitude: 103.8380, details: JSON.stringify({ lines: ['NSL', 'DTL'], interchange: true }) },
  { category: 'mrt', name: 'Little India MRT (NE7/DT12)', latitude: 1.3068, longitude: 103.8492, details: JSON.stringify({ lines: ['NEL', 'DTL'], interchange: true }) },
  { category: 'mrt', name: 'Rochor MRT (DT13)', latitude: 1.3038, longitude: 103.8526, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Bugis MRT (EW12/DT14)', latitude: 1.3002, longitude: 103.8560, details: JSON.stringify({ lines: ['EWL', 'DTL'], interchange: true }) },
  { category: 'mrt', name: 'Promenade MRT (CC4/DT15)', latitude: 1.2930, longitude: 103.8604, details: JSON.stringify({ lines: ['CCL', 'DTL'], interchange: true }) },
  { category: 'mrt', name: 'Bayfront MRT (DT16/CE1)', latitude: 1.2818, longitude: 103.8591, details: JSON.stringify({ lines: ['DTL', 'CCL'], interchange: true }) },
  { category: 'mrt', name: 'Downtown MRT (DT17)', latitude: 1.2794, longitude: 103.8528, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Telok Ayer MRT (DT18)', latitude: 1.2821, longitude: 103.8486, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Chinatown MRT (NE4/DT19)', latitude: 1.2844, longitude: 103.8437, details: JSON.stringify({ lines: ['NEL', 'DTL'], interchange: true }) },
  { category: 'mrt', name: 'Fort Canning MRT (DT20)', latitude: 1.2924, longitude: 103.8443, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Bencoolen MRT (DT21)', latitude: 1.2987, longitude: 103.8504, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Jalan Besar MRT (DT22)', latitude: 1.3052, longitude: 103.8552, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Bendemeer MRT (DT23)', latitude: 1.3137, longitude: 103.8630, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Geylang Bahru MRT (DT24)', latitude: 1.3213, longitude: 103.8715, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Mattar MRT (DT25)', latitude: 1.3268, longitude: 103.8833, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'MacPherson MRT (CC10/DT26)', latitude: 1.3262, longitude: 103.8900, details: JSON.stringify({ lines: ['CCL', 'DTL'], interchange: true }) },
  { category: 'mrt', name: 'Ubi MRT (DT27)', latitude: 1.3298, longitude: 103.8993, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Kaki Bukit MRT (DT28)', latitude: 1.3349, longitude: 103.9086, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Bedok North MRT (DT29)', latitude: 1.3347, longitude: 103.9180, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Bedok Reservoir MRT (DT30)', latitude: 1.3366, longitude: 103.9323, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Tampines West MRT (DT31)', latitude: 1.3456, longitude: 103.9384, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Tampines MRT (EW2/DT32)', latitude: 1.3532, longitude: 103.9452, details: JSON.stringify({ lines: ['EWL', 'DTL'], interchange: true }) },
  { category: 'mrt', name: 'Tampines East MRT (DT33)', latitude: 1.3562, longitude: 103.9546, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Upper Changi MRT (DT34)', latitude: 1.3417, longitude: 103.9614, details: JSON.stringify({ lines: ['DTL'], interchange: false }) },
  { category: 'mrt', name: 'Expo MRT (CG1/DT35)', latitude: 1.3353, longitude: 103.9623, details: JSON.stringify({ lines: ['EWL', 'DTL'], interchange: true }) },

  // Thomson-East Coast Line (TEL - Brown Line) 🟤
  { category: 'mrt', name: 'Woodlands North MRT (TE1)', latitude: 1.4482, longitude: 103.7857, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Woodlands South MRT (TE3)', latitude: 1.4274, longitude: 103.7933, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Springleaf MRT (TE4)', latitude: 1.3976, longitude: 103.8182, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Lentor MRT (TE5)', latitude: 1.3855, longitude: 103.8360, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Mayflower MRT (TE6)', latitude: 1.3714, longitude: 103.8365, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Bright Hill MRT (TE7)', latitude: 1.3633, longitude: 103.8335, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Upper Thomson MRT (TE8)', latitude: 1.3544, longitude: 103.8329, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Caldecott MRT (CC17/TE9)', latitude: 1.3377, longitude: 103.8400, details: JSON.stringify({ lines: ['CCL', 'TEL'], interchange: true }) },
  { category: 'mrt', name: 'Napier MRT (TE12)', latitude: 1.3068, longitude: 103.8185, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Orchard Boulevard MRT (TE13)', latitude: 1.3023, longitude: 103.8238, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Great World MRT (TE15)', latitude: 1.2936, longitude: 103.8321, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Havelock MRT (TE16)', latitude: 1.2886, longitude: 103.8327, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Maxwell MRT (TE18)', latitude: 1.2804, longitude: 103.8443, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Shenton Way MRT (TE19)', latitude: 1.2778, longitude: 103.8502, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Gardens by the Bay MRT (TE22)', latitude: 1.2818, longitude: 103.8672, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Marine Parade MRT (TE26)', latitude: 1.3025, longitude: 103.9050, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Marine Terrace MRT (TE27)', latitude: 1.3060, longitude: 103.9160, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Siglap MRT (TE28)', latitude: 1.3110, longitude: 103.9280, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },
  { category: 'mrt', name: 'Bayshore MRT (TE29)', latitude: 1.3180, longitude: 103.9400, details: JSON.stringify({ lines: ['TEL'], interchange: false }) },

  // Circle Line (CCL - Yellow Line) 🟡 & Other Trunk Interchanges
  { category: 'mrt', name: 'Holland Village MRT (CC21)', latitude: 1.3116, longitude: 103.7961, details: JSON.stringify({ lines: ['CCL'], interchange: false }) },
  { category: 'mrt', name: 'Farrer Road MRT (CC20)', latitude: 1.3175, longitude: 103.8078, details: JSON.stringify({ lines: ['CCL'], interchange: false }) },
  { category: 'mrt', name: 'one-north MRT (CC23)', latitude: 1.2996, longitude: 103.7872, details: JSON.stringify({ lines: ['CCL'], interchange: false }) },
  { category: 'mrt', name: 'Kent Ridge MRT (CC24)', latitude: 1.2935, longitude: 103.7845, details: JSON.stringify({ lines: ['CCL'], interchange: false }) },
  { category: 'mrt', name: 'Haw Par Villa MRT (CC25)', latitude: 1.2825, longitude: 103.7818, details: JSON.stringify({ lines: ['CCL'], interchange: false }) },
  { category: 'mrt', name: 'Labrador Park MRT (CC27)', latitude: 1.2722, longitude: 103.8030, details: JSON.stringify({ lines: ['CCL'], interchange: false }) },
  { category: 'mrt', name: 'HarbourFront MRT (NE1/CC29)', latitude: 1.2653, longitude: 103.8215, details: JSON.stringify({ lines: ['NEL', 'CCL'], interchange: true }) },

  // East West (Green Line) & North South (Red Line)
  { category: 'mrt', name: 'Orchard MRT (NS22/TE14)', latitude: 1.3040, longitude: 103.8318, details: JSON.stringify({ lines: ['NSL', 'TEL'], interchange: true }) },
  { category: 'mrt', name: 'Somerset MRT (NS23)', latitude: 1.3002, longitude: 103.8390, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Dhoby Ghaut MRT (NS24/NE6/CC1)', latitude: 1.2987, longitude: 103.8461, details: JSON.stringify({ lines: ['NSL', 'NEL', 'CCL'], interchange: true }) },
  { category: 'mrt', name: 'City Hall MRT (NS25/EW13)', latitude: 1.2929, longitude: 103.8525, details: JSON.stringify({ lines: ['NSL', 'EWL'], interchange: true }) },
  { category: 'mrt', name: 'Raffles Place MRT (NS26/EW14)', latitude: 1.2841, longitude: 103.8515, details: JSON.stringify({ lines: ['NSL', 'EWL'], interchange: true }) },
  { category: 'mrt', name: 'Marina Bay MRT (NS27/CE2/TE20)', latitude: 1.2764, longitude: 103.8546, details: JSON.stringify({ lines: ['NSL', 'CCL', 'TEL'], interchange: true }) },
  { category: 'mrt', name: 'Tanjong Pagar MRT (EW15)', latitude: 1.2765, longitude: 103.8458, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Outram Park MRT (EW16/NE3/TE17)', latitude: 1.2803, longitude: 103.8395, details: JSON.stringify({ lines: ['EWL', 'NEL', 'TEL'], interchange: true }) },
  { category: 'mrt', name: 'Tiong Bahru MRT (EW17)', latitude: 1.2861, longitude: 103.8270, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Redhill MRT (EW18)', latitude: 1.2896, longitude: 103.8168, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Queenstown MRT (EW19)', latitude: 1.2949, longitude: 103.8060, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Commonwealth MRT (EW20)', latitude: 1.2996, longitude: 103.7982, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Buona Vista MRT (EW21/CC22)', latitude: 1.3073, longitude: 103.7900, details: JSON.stringify({ lines: ['EWL', 'CCL'], interchange: true }) },
  { category: 'mrt', name: 'Dover MRT (EW22)', latitude: 1.3114, longitude: 103.7786, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Clementi MRT (EW23)', latitude: 1.3151, longitude: 103.7652, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Jurong East MRT (NS1/EW24)', latitude: 1.3332, longitude: 103.7423, details: JSON.stringify({ lines: ['NSL', 'EWL'], interchange: true }) },
  { category: 'mrt', name: 'Lakeside MRT (EW26)', latitude: 1.3442, longitude: 103.7210, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Boon Lay MRT (EW27)', latitude: 1.3386, longitude: 103.7060, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Novena MRT (NS20)', latitude: 1.3204, longitude: 103.8438, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Toa Payoh MRT (NS19)', latitude: 1.3326, longitude: 103.8475, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Bishan MRT (NS17/CC15)', latitude: 1.3508, longitude: 103.8482, details: JSON.stringify({ lines: ['NSL', 'CCL'], interchange: true }) },
  { category: 'mrt', name: 'Ang Mo Kio MRT (NS16)', latitude: 1.3699, longitude: 103.8496, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Yishun MRT (NS13)', latitude: 1.4294, longitude: 103.8350, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Khatib MRT (NS14)', latitude: 1.4173, longitude: 103.8330, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Sembawang MRT (NS11)', latitude: 1.4490, longitude: 103.8201, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Canberra MRT (NS12)', latitude: 1.4431, longitude: 103.8297, details: JSON.stringify({ lines: ['NSL'], interchange: false }) },
  { category: 'mrt', name: 'Woodlands MRT (NS9/TE2)', latitude: 1.4369, longitude: 103.7865, details: JSON.stringify({ lines: ['NSL', 'TEL'], interchange: true }) },
  { category: 'mrt', name: 'Paya Lebar MRT (EW8/CC9)', latitude: 1.3178, longitude: 103.8924, details: JSON.stringify({ lines: ['EWL', 'CCL'], interchange: true }) },
  { category: 'mrt', name: 'Eunos MRT (EW7)', latitude: 1.3197, longitude: 103.9030, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Bedok MRT (EW5)', latitude: 1.3240, longitude: 103.9300, details: JSON.stringify({ lines: ['EWL'], interchange: false }) },
  { category: 'mrt', name: 'Serangoon MRT (NE12/CC13)', latitude: 1.3497, longitude: 103.8736, details: JSON.stringify({ lines: ['NEL', 'CCL'], interchange: true }) },
  { category: 'mrt', name: 'Kovan MRT (NE13)', latitude: 1.3602, longitude: 103.8850, details: JSON.stringify({ lines: ['NEL'], interchange: false }) },
  { category: 'mrt', name: 'Hougang MRT (NE14)', latitude: 1.3713, longitude: 103.8924, details: JSON.stringify({ lines: ['NEL'], interchange: false }) },
  { category: 'mrt', name: 'Sengkang MRT (NE16/STC)', latitude: 1.3917, longitude: 103.8955, details: JSON.stringify({ lines: ['NEL', 'LRT'], interchange: true }) },
  { category: 'mrt', name: 'Punggol MRT (NE17/PTC)', latitude: 1.4049, longitude: 103.9021, details: JSON.stringify({ lines: ['NEL', 'LRT'], interchange: true }) },

  // ==================== 🏫 PRIMARY SCHOOLS ====================
  { category: 'school', name: 'Methodist Girls\' School (Primary)', latitude: 1.3340, longitude: 103.7800, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'Bukit Timah Primary School', latitude: 1.3410, longitude: 103.7690, details: JSON.stringify({ popular: false }) },
  { category: 'school', name: 'Nanyang Primary School', latitude: 1.3195, longitude: 103.8078, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'Raffles Girls\' Primary School', latitude: 1.3298, longitude: 103.8062, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'Anglo-Chinese School (Primary)', latitude: 1.3182, longitude: 103.8374, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'Anglo-Chinese School (Junior)', latitude: 1.3088, longitude: 103.8398, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'Catholic High School (Primary)', latitude: 1.3547, longitude: 103.8450, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'St. Hilda\'s Primary School', latitude: 1.3508, longitude: 103.9372, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'Tao Nan School', latitude: 1.3045, longitude: 103.9090, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'Henry Park Primary School', latitude: 1.3168, longitude: 103.7845, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'Ai Tong School', latitude: 1.3605, longitude: 103.8368, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'Pei Hwa Presbyterian Primary School', latitude: 1.3381, longitude: 103.7760, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'Radin Mas Primary School', latitude: 1.2758, longitude: 103.8241, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'Alexandra Primary School', latitude: 1.2912, longitude: 103.8245, details: JSON.stringify({ popular: false }) },
  { category: 'school', name: 'Cantonment Primary School', latitude: 1.2752, longitude: 103.8402, details: JSON.stringify({ popular: false }) },
  { category: 'school', name: 'Fairfield Methodist School (Primary)', latitude: 1.3005, longitude: 103.7825, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'Nan Hua Primary School', latitude: 1.3190, longitude: 103.7602, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'River Valley Primary School', latitude: 1.2946, longitude: 103.8360, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'St. Joseph\'s Institution Junior', latitude: 1.3189, longitude: 103.8472, details: JSON.stringify({ popular: true }) },
  { category: 'school', name: 'Hong Kah Primary School', latitude: 1.3502, longitude: 103.7420, details: JSON.stringify({ popular: false }) },
  { category: 'school', name: 'Chij St. Nicholas Girls\' School', latitude: 1.3734, longitude: 103.8340, details: JSON.stringify({ popular: true, geip: true }) },
  { category: 'school', name: 'Maha Bodhi School', latitude: 1.3275, longitude: 103.9015, details: JSON.stringify({ popular: true }) },

  // ==================== 🍜 HAWKER CENTRES ====================
  { category: 'hawker', name: 'Maxwell Food Centre', latitude: 1.2803, longitude: 103.8447, details: JSON.stringify({ famousFor: 'Tian Tian Chicken Rice' }) },
  { category: 'hawker', name: 'Lau Pa Sat (Telok Ayer Market)', latitude: 1.2806, longitude: 103.8504, details: JSON.stringify({ famousFor: 'Satay Street' }) },
  { category: 'hawker', name: 'Old Airport Road Food Centre', latitude: 1.3082, longitude: 103.8858, details: JSON.stringify({ famousFor: 'Char Kway Teow, Lor Mee' }) },
  { category: 'hawker', name: 'Tiong Bahru Market & Food Centre', latitude: 1.2852, longitude: 103.8324, details: JSON.stringify({ famousFor: 'Chwee Kueh, Roast Meats' }) },
  { category: 'hawker', name: 'Newton Food Centre', latitude: 1.3120, longitude: 103.8394, details: JSON.stringify({ famousFor: 'Seafood Satay' }) },
  { category: 'hawker', name: 'Amoy Street Food Centre', latitude: 1.2792, longitude: 103.8467, details: JSON.stringify({ famousFor: 'Michelin Bib Gourmand Stalls' }) },
  { category: 'hawker', name: 'Chomp Chomp Food Centre', latitude: 1.3643, longitude: 103.8665, details: JSON.stringify({ famousFor: 'BBQ Sambal Stingray, Hokkien Mee' }) },
  { category: 'hawker', name: 'Ghim Moh Market & Food Centre', latitude: 1.3110, longitude: 103.7882, details: JSON.stringify({ famousFor: 'Duck Rice, Appam' }) },
  { category: 'hawker', name: 'ABC Brickworks Food Centre', latitude: 1.2869, longitude: 103.8080, details: JSON.stringify({ famousFor: 'Claypot Rice' }) },
  { category: 'hawker', name: 'Adam Road Food Centre', latitude: 1.3241, longitude: 103.8142, details: JSON.stringify({ famousFor: 'Nasi Lemak' }) },
  { category: 'hawker', name: 'Tekka Centre', latitude: 1.3060, longitude: 103.8507, details: JSON.stringify({ famousFor: 'Indian Cuisine, Briyani' }) },
  { category: 'hawker', name: 'Golden Mile Food Centre', latitude: 1.3031, longitude: 103.8638, details: JSON.stringify({ famousFor: 'Sup Tulang, Claypot Rice' }) },
  { category: 'hawker', name: 'Chinatown Complex Food Centre', latitude: 1.2824, longitude: 103.8432, details: JSON.stringify({ famousFor: 'Liao Fan Soy Sauce Chicken' }) },
  { category: 'hawker', name: 'Zion Riverside Food Centre', latitude: 1.2930, longitude: 103.8335, details: JSON.stringify({ famousFor: 'Zion Rd Fried Kway Teow' }) },
  { category: 'hawker', name: 'Bedok Interchange Food Centre', latitude: 1.3248, longitude: 103.9302, details: JSON.stringify({ famousFor: 'Bak Chor Mee, Bedok Chwee Kueh' }) },
  { category: 'hawker', name: 'East Coast Lagoon Food Village', latitude: 1.3070, longitude: 103.9348, details: JSON.stringify({ famousFor: 'Beachfront BBQ Seafood' }) },
  { category: 'hawker', name: 'Ayer Rajah Food Centre', latitude: 1.3075, longitude: 103.7598, details: JSON.stringify({ famousFor: 'Indian Muslim Food, Mee Goreng' }) },

  // ==================== 🛒 SUPERMARKETS & MALLS ====================
  { category: 'supermarket', name: 'NTUC FairPrice Finest - Scotts Square', latitude: 1.3065, longitude: 103.8328, details: JSON.stringify({ type: 'Supermarket' }) },
  { category: 'supermarket', name: 'Don Don Donki - Orchard Central', latitude: 1.3006, longitude: 103.8398, details: JSON.stringify({ type: 'Japanese Specialty Store' }) },
  { category: 'supermarket', name: 'Cold Storage - Great World City', latitude: 1.2935, longitude: 103.8319, details: JSON.stringify({ type: 'Supermarket' }) },
  { category: 'supermarket', name: 'ION Orchard Shopping Mall', latitude: 1.3040, longitude: 103.8320, details: JSON.stringify({ type: 'Shopping Mall' }) },
  { category: 'supermarket', name: 'Plaza Singapura & FairPrice PS', latitude: 1.2990, longitude: 103.8452, details: JSON.stringify({ type: 'Mall & Supermarket' }) },
  { category: 'supermarket', name: 'VivoCity & FairPrice Xtra', latitude: 1.2644, longitude: 103.8222, details: JSON.stringify({ type: 'Mall & Hypermarket' }) },
  { category: 'supermarket', name: 'Sheng Siong Supermarket - Tanglin Halt', latitude: 1.2998, longitude: 103.7990, details: JSON.stringify({ type: 'Supermarket' }) },
  { category: 'supermarket', name: 'Cold Storage - Jelita Shopping Centre', latitude: 1.3162, longitude: 103.7850, details: JSON.stringify({ type: 'Supermarket' }) },
  { category: 'supermarket', name: 'JEM & Westgate Shopping Malls', latitude: 1.3330, longitude: 103.7430, details: JSON.stringify({ type: 'Shopping Mall' }) },
  { category: 'supermarket', name: 'Nex Mall & FairPrice Xtra - Serangoon', latitude: 1.3506, longitude: 103.8722, details: JSON.stringify({ type: 'Mall & Hypermarket' }) },
  { category: 'supermarket', name: 'Tampines Mall & Century Square', latitude: 1.3528, longitude: 103.9446, details: JSON.stringify({ type: 'Shopping Mall' }) },
  { category: 'supermarket', name: 'Northpoint City - Yishun', latitude: 1.4290, longitude: 103.8360, details: JSON.stringify({ type: 'Shopping Mall' }) },
  { category: 'supermarket', name: 'Bugis Junction & Bugis+', latitude: 1.3005, longitude: 103.8552, details: JSON.stringify({ type: 'Shopping Mall' }) },
  { category: 'supermarket', name: 'NTUC FairPrice Finest - Bukit Timah Plaza', latitude: 1.3375, longitude: 103.7780, details: JSON.stringify({ type: 'Supermarket' }) },

  // ==================== 🌳 PARKS & GREENERY ====================
  // Central & Bukit Timah
  { category: 'park', name: 'Rifle Range Nature Park (Binjai Trailhead)', latitude: 1.3440, longitude: 103.7845, details: JSON.stringify({ type: 'Nature Park & Rainforest Trail' }) },
  { category: 'park', name: 'Rifle Range Nature Park (Visitor Centre)', latitude: 1.3485, longitude: 103.7788, details: JSON.stringify({ type: 'Nature Park & Visitor Centre' }) },
  { category: 'park', name: 'Bukit Timah Nature Reserve (Main Summit)', latitude: 1.3547, longitude: 103.7762, details: JSON.stringify({ type: 'Primary Rainforest' }) },
  { category: 'park', name: 'Hindhede Nature Park', latitude: 1.3508, longitude: 103.7745, details: JSON.stringify({ type: 'Quarry Park' }) },
  { category: 'park', name: 'Dairy Farm Nature Park', latitude: 1.3620, longitude: 103.7730, details: JSON.stringify({ type: 'Nature Park' }) },
  { category: 'park', name: 'Chestnut Nature Park (North)', latitude: 1.3750, longitude: 103.7735, details: JSON.stringify({ type: 'Nature Park' }) },
  { category: 'park', name: 'Chestnut Nature Park (South)', latitude: 1.3710, longitude: 103.7705, details: JSON.stringify({ type: 'Nature Park' }) },
  { category: 'park', name: 'Zhenghua Nature Park', latitude: 1.3780, longitude: 103.7660, details: JSON.stringify({ type: 'Linear Park' }) },
  { category: 'park', name: 'Singapore Botanic Gardens (UNESCO)', latitude: 1.3138, longitude: 103.8159, details: JSON.stringify({ type: 'UNESCO Heritage Park' }) },

  // Bishan, Ang Mo Kio, Thomson & Central Catchment
  { category: 'park', name: 'Bishan-Ang Mo Kio Park (River Plains)', latitude: 1.3625, longitude: 103.8460, details: JSON.stringify({ type: 'Riverine Park' }) },
  { category: 'park', name: 'Bishan-Ang Mo Kio Park (Pond Gardens)', latitude: 1.3650, longitude: 103.8375, details: JSON.stringify({ type: 'Riverine Park' }) },
  { category: 'park', name: 'Ang Mo Kio Town Garden East', latitude: 1.3710, longitude: 103.8480, details: JSON.stringify({ type: 'Town Park' }) },
  { category: 'park', name: 'Ang Mo Kio Town Garden West', latitude: 1.3700, longitude: 103.8390, details: JSON.stringify({ type: 'Town Park' }) },
  { category: 'park', name: 'MacRitchie Reservoir Park (Lornie Trailhead)', latitude: 1.3440, longitude: 103.8340, details: JSON.stringify({ type: 'Reservoir & Treetop Walk' }) },
  { category: 'park', name: 'MacRitchie Reservoir (Venus Drive Entrance)', latitude: 1.3585, longitude: 103.8320, details: JSON.stringify({ type: 'Treetop Walk Trailhead' }) },
  { category: 'park', name: 'Thomson Nature Park', latitude: 1.3810, longitude: 103.8260, details: JSON.stringify({ type: 'Heritage Nature Park' }) },
  { category: 'park', name: 'Lower Peirce Reservoir Park', latitude: 1.3715, longitude: 103.8265, details: JSON.stringify({ type: 'Reservoir Park' }) },
  { category: 'park', name: 'Upper Peirce Reservoir Park', latitude: 1.3700, longitude: 103.8120, details: JSON.stringify({ type: 'Reservoir Park' }) },
  { category: 'park', name: 'Central Catchment Nature Reserve', latitude: 1.3680, longitude: 103.8120, details: JSON.stringify({ type: 'Nature Reserve' }) },

  // Town, Downtown & South
  { category: 'park', name: 'Fort Canning Park', latitude: 1.2952, longitude: 103.8465, details: JSON.stringify({ type: 'Historic Hill Park' }) },
  { category: 'park', name: 'Gardens by the Bay (Supertree Grove)', latitude: 1.2815, longitude: 103.8636, details: JSON.stringify({ type: 'Iconic Nature Park' }) },
  { category: 'park', name: 'Gardens by the Bay (Bay East)', latitude: 1.2930, longitude: 103.8710, details: JSON.stringify({ type: 'Waterfront Park' }) },
  { category: 'park', name: 'Pearl\'s Hill City Park', latitude: 1.2845, longitude: 103.8410, details: JSON.stringify({ type: 'Hilltop Park' }) },
  { category: 'park', name: 'Mount Emily Park', latitude: 1.3045, longitude: 103.8485, details: JSON.stringify({ type: 'Hilltop Park' }) },

  // Southern Ridges & Queenstown
  { category: 'park', name: 'Southern Ridges & Mount Faber Park', latitude: 1.2760, longitude: 103.8180, details: JSON.stringify({ type: 'Hill Canopy Walk' }) },
  { category: 'park', name: 'Telok Blangah Hill Park', latitude: 1.2780, longitude: 103.8100, details: JSON.stringify({ type: 'Canopy Walk Park' }) },
  { category: 'park', name: 'HortPark (Gardens Hub)', latitude: 1.2790, longitude: 103.7990, details: JSON.stringify({ type: 'Gardening Hub' }) },
  { category: 'park', name: 'Kent Ridge Park', latitude: 1.2860, longitude: 103.7900, details: JSON.stringify({ type: 'Historical Park' }) },
  { category: 'park', name: 'Labrador Nature Reserve', latitude: 1.2660, longitude: 103.8020, details: JSON.stringify({ type: 'Coastal Cliff Reserve' }) },
  { category: 'park', name: 'Tiong Bahru Park', latitude: 1.2885, longitude: 103.8235, details: JSON.stringify({ type: 'Neighborhood Park' }) },

  // West & Jurong
  { category: 'park', name: 'West Coast Park (Area 2 Main)', latitude: 1.2980, longitude: 103.7660, details: JSON.stringify({ type: 'Regional Coastal Park' }) },
  { category: 'park', name: 'Clementi Woods Park', latitude: 1.3030, longitude: 103.7680, details: JSON.stringify({ type: 'Neighborhood Park' }) },
  { category: 'park', name: 'Jurong Lake Gardens (Lakeside)', latitude: 1.3360, longitude: 103.7290, details: JSON.stringify({ type: 'Lakeside Park' }) },
  { category: 'park', name: 'Jurong Lake Gardens (Chinese & Japanese Gardens)', latitude: 1.3390, longitude: 103.7330, details: JSON.stringify({ type: 'Cultural Gardens' }) },
  { category: 'park', name: 'Jurong Central Park', latitude: 1.3260, longitude: 103.7040, details: JSON.stringify({ type: 'Town Park' }) },

  // North & North-West
  { category: 'park', name: 'Sungei Buloh Wetland Reserve (Visitor Centre)', latitude: 1.4460, longitude: 103.7300, details: JSON.stringify({ type: 'Wetland Reserve' }) },
  { category: 'park', name: 'Sungei Buloh (Extension Entrance)', latitude: 1.4410, longitude: 103.7250, details: JSON.stringify({ type: 'Wetland Reserve' }) },
  { category: 'park', name: 'Admiralty Park', latitude: 1.4450, longitude: 103.7780, details: JSON.stringify({ type: 'Nature Park' }) },
  { category: 'park', name: 'Woodlands Waterfront Park', latitude: 1.4540, longitude: 103.7800, details: JSON.stringify({ type: 'Coastal Promenade' }) },
  { category: 'park', name: 'Sembawang Park', latitude: 1.4630, longitude: 103.8360, details: JSON.stringify({ type: 'Beachfront Park' }) },
  { category: 'park', name: 'Yishun Park', latitude: 1.4230, longitude: 103.8430, details: JSON.stringify({ type: 'Regional Park' }) },
  { category: 'park', name: 'Yishun Pond Park', latitude: 1.4280, longitude: 103.8380, details: JSON.stringify({ type: 'Pond Park' }) },
  { category: 'park', name: 'Lower Seletar Reservoir Park', latitude: 1.4120, longitude: 103.8360, details: JSON.stringify({ type: 'Reservoir Park' }) },
  { category: 'park', name: 'Springleaf Nature Park', latitude: 1.3980, longitude: 103.8180, details: JSON.stringify({ type: 'Riverine Nature Park' }) },

  // North-East (Sengkang, Punggol, Hougang)
  { category: 'park', name: 'Sengkang Riverside Park', latitude: 1.3960, longitude: 103.8860, details: JSON.stringify({ type: 'Riverine Wetland Park' }) },
  { category: 'park', name: 'Punggol Waterway Park (Sentul Crescent)', latitude: 1.4110, longitude: 103.9060, details: JSON.stringify({ type: 'Waterway Park' }) },
  { category: 'park', name: 'Punggol Waterway Park (Sunrise Bridge)', latitude: 1.4050, longitude: 103.9210, details: JSON.stringify({ type: 'Sunrise Promenade' }) },
  { category: 'park', name: 'Coney Island Park (West Entrance)', latitude: 1.4130, longitude: 103.9160, details: JSON.stringify({ type: 'Island Nature Park' }) },
  { category: 'park', name: 'Coney Island Park (East Entrance)', latitude: 1.4090, longitude: 103.9310, details: JSON.stringify({ type: 'Island Nature Park' }) },
  { category: 'park', name: 'Punggol Park (Hougang)', latitude: 1.3780, longitude: 103.8960, details: JSON.stringify({ type: 'Neighborhood Park' }) },

  // East & East Coast
  { category: 'park', name: 'East Coast Park (Area B - Parkland Green)', latitude: 1.3008, longitude: 103.9010, details: JSON.stringify({ type: 'Coastal Park' }) },
  { category: 'park', name: 'East Coast Park (Area C - Marine Cove)', latitude: 1.3008, longitude: 103.9120, details: JSON.stringify({ type: 'Coastal Park' }) },
  { category: 'park', name: 'East Coast Park (Area E - Lagoon & PCN)', latitude: 1.3070, longitude: 103.9350, details: JSON.stringify({ type: 'Coastal Park' }) },
  { category: 'park', name: 'East Coast Park (Area G - Bedok Jetty)', latitude: 1.3060, longitude: 103.9240, details: JSON.stringify({ type: 'Coastal Jetty Park' }) },
  { category: 'park', name: 'Bedok Reservoir Park (West Entrance)', latitude: 1.3380, longitude: 103.9240, details: JSON.stringify({ type: 'Reservoir Park' }) },
  { category: 'park', name: 'Bedok Reservoir Park (Floating Deck)', latitude: 1.3420, longitude: 103.9310, details: JSON.stringify({ type: 'Reservoir Park' }) },
  { category: 'park', name: 'Tampines Eco Green', latitude: 1.3590, longitude: 103.9480, details: JSON.stringify({ type: 'Eco Park' }) },
  { category: 'park', name: 'Tampines Central Park', latitude: 1.3540, longitude: 103.9410, details: JSON.stringify({ type: 'Town Park' }) },
  { category: 'park', name: 'Sun Plaza Park (Tampines)', latitude: 1.3570, longitude: 103.9440, details: JSON.stringify({ type: 'Town Park' }) },
  { category: 'park', name: 'Pasir Ris Park (Area 1 Beach)', latitude: 1.3768, longitude: 103.9540, details: JSON.stringify({ type: 'Coastal Park & Beach' }) },
  { category: 'park', name: 'Pasir Ris Park (Area 3 Mangrove Boardwalk)', latitude: 1.3740, longitude: 103.9480, details: JSON.stringify({ type: 'Mangrove Boardwalk' }) },
  { category: 'park', name: 'Changi Beach Park (Car Park 1)', latitude: 1.3890, longitude: 103.9880, details: JSON.stringify({ type: 'Coastal Park' }) },
  { category: 'park', name: 'Changi Beach Park (Changi Village)', latitude: 1.3910, longitude: 103.9820, details: JSON.stringify({ type: 'Coastal Promenade' }) }
];
